// Generated by logos-lidl-gen from the `bc_probe` LIDL contract — do not edit.
//
// Typed caller + event subscribers over logos_rust_sdk's lp_* consumer.

use logos_rust_sdk::{EventData, EventSubscription, LogosError, LogosModuleSDK, PluginProxy, RestartPolicy, SubStatus};

pub struct BcProbeClient {
    proxy: PluginProxy,
}

impl BcProbeClient {
    /// Client bound to the contract's own module name (`bc_probe`) —
    /// the concrete-dependency pattern.
    pub fn new() -> Self {
        Self { proxy: LogosModuleSDK::new().plugin("bc_probe") }
    }

    /// Bind the same typed surface to ANY provider chosen at runtime —
    /// the interface-dependency pattern: the contract names the shape,
    /// the caller names the module.
    pub fn bind(module_name: &str) -> Self {
        Self { proxy: LogosModuleSDK::new().plugin(module_name) }
    }

    pub fn chain_info_via_bc(&self) -> Result<std::collections::BTreeMap<String, serde_json::Value>, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("chain_info_via_bc", &args)?;
        (|| Some((&value).as_object()?.iter().map(|(__k, __v)| Some((__k.clone(), __v.clone()))).collect::<Option<std::collections::BTreeMap<_, _>>>()?))().ok_or_else(|| logos_rust_sdk::LogosError::JsonError("result does not match the declared collection type".to_string()))
    }

    /// [`Self::chain_info_via_bc`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::chain_info_via_bc`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn chain_info_via_bc_with_timeout(&self, timeout: std::time::Duration) -> Result<std::collections::BTreeMap<String, serde_json::Value>, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json_with_timeout("chain_info_via_bc", &args, timeout)?;
        (|| Some((&value).as_object()?.iter().map(|(__k, __v)| Some((__k.clone(), __v.clone()))).collect::<Option<std::collections::BTreeMap<_, _>>>()?))().ok_or_else(|| logos_rust_sdk::LogosError::JsonError("result does not match the declared collection type".to_string()))
    }

    /// Async twin of [`Self::chain_info_via_bc`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `chain_info_via_bcAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn chain_info_via_bc_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<std::collections::BTreeMap<String, serde_json::Value>, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("chain_info_via_bc", &args, move |result| {
            callback(result.and_then(|value| (|| Some((&value).as_object()?.iter().map(|(__k, __v)| Some((__k.clone(), __v.clone()))).collect::<Option<std::collections::BTreeMap<_, _>>>()?))().ok_or_else(|| logos_rust_sdk::LogosError::JsonError("result does not match the declared collection type".to_string()))));
        });
    }

    /// [`Self::chain_info_via_bc_async`] with a per-call timeout — the async half of
    /// [`Self::chain_info_via_bc_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::chain_info_via_bc_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn chain_info_via_bc_async_with_timeout<F>(&self, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<std::collections::BTreeMap<String, serde_json::Value>, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async_with_timeout("chain_info_via_bc", &args, timeout, move |result| {
            callback(result.and_then(|value| (|| Some((&value).as_object()?.iter().map(|(__k, __v)| Some((__k.clone(), __v.clone()))).collect::<Option<std::collections::BTreeMap<_, _>>>()?))().ok_or_else(|| logos_rust_sdk::LogosError::JsonError("result does not match the declared collection type".to_string()))));
        });
    }

    /// The module's name, as declared in its metadata.
    pub fn name(&self) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("name", &args)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// [`Self::name`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::name`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn name_with_timeout(&self, timeout: std::time::Duration) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json_with_timeout("name", &args, timeout)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// Async twin of [`Self::name`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `nameAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn name_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("name", &args, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// [`Self::name_async`] with a per-call timeout — the async half of
    /// [`Self::name_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::name_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn name_async_with_timeout<F>(&self, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async_with_timeout("name", &args, timeout, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// The module's version, as declared in its metadata.
    pub fn version(&self) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("version", &args)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// [`Self::version`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::version`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn version_with_timeout(&self, timeout: std::time::Duration) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json_with_timeout("version", &args, timeout)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// Async twin of [`Self::version`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `versionAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn version_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("version", &args, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// [`Self::version_async`] with a per-call timeout — the async half of
    /// [`Self::version_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::version_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn version_async_with_timeout<F>(&self, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async_with_timeout("version", &args, timeout, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// The module's canonical LIDL interface document.
    pub fn lidl(&self) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("lidl", &args)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// [`Self::lidl`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::lidl`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn lidl_with_timeout(&self, timeout: std::time::Duration) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json_with_timeout("lidl", &args, timeout)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// Async twin of [`Self::lidl`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `lidlAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn lidl_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("lidl", &args, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// [`Self::lidl_async`] with a per-call timeout — the async half of
    /// [`Self::lidl_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::lidl_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn lidl_async_with_timeout<F>(&self, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async_with_timeout("lidl", &args, timeout, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }
}

impl Default for BcProbeClient {
    fn default() -> Self {
        Self::new()
    }
}
