[workspace]
members = ["demo-core", "headless", "app"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
logos-rust-sdk = { git = "https://github.com/logos-co/logos-rust-sdk", rev = "42f6a7ed313e10fa552471b07334b7ac7eb24640", features = ["host"] }
serde_json = "1"
demo-core = { path = "demo-core" }
