// bc-watch: the demo's node, read from C++ with no Qt. It runs a Logos runtime
// of its own, links a daemon, imports that daemon's blockchain_module, and
// prints the chain state and each new block, through clients generated by
// logos-cpp-generator (logos_generate_clients in CMakeLists.txt).
//
//   bc-watch --runtime DIR --modules DIR --data DIR --tmp DIR
//            (--link-local FILE | --invite FILE) [--remote-module NAME] [--seconds N]

#include "blockchain_module_api.h"
#include "peering_module_api.h"

#include <logos_host_core.h>

#include <atomic>
#include <chrono>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <thread>

namespace {

constexpr const char* kShell = "bc_watch";
constexpr const char* kNode = "blockchain_module";

[[noreturn]] void fail(const std::string& step, const std::string& error)
{
    std::cout << nlohmann::json{{"step", step}, {"error", error}}.dump() << std::endl;
    std::exit(1);
}

void emit(const std::string& step, const nlohmann::json& result)
{
    std::cout << nlohmann::json{{"step", step}, {"result", result}}.dump() << std::endl;
}

template <class Ready>
bool waitFor(std::chrono::seconds limit, Ready ready)
{
    const auto deadline = std::chrono::steady_clock::now() + limit;
    while (std::chrono::steady_clock::now() < deadline) {
        if (ready()) return true;
        std::this_thread::sleep_for(std::chrono::milliseconds(250));
    }
    return false;
}

std::string firstLine(const std::string& path)
{
    std::ifstream in(path);
    std::string line;
    if (!in || !std::getline(in, line)) fail("invite", "cannot read " + path);
    return line;
}

// logos-pair:v1:<runtime id>:<root digest>:<secret>@<host>:<port>
std::string inviteRuntimeId(const std::string& invite)
{
    const std::string prefix = "logos-pair:v1:";
    if (invite.rfind(prefix, 0) != 0) fail("invite", "not a Logos invite");
    const auto rest = invite.substr(prefix.size());
    return rest.substr(0, rest.find(':'));
}

// blockchain_module answers its info as a JSON document in `value`.
nlohmann::json valueOf(const StdLogosResult& reply)
{
    if (!reply.success) return nlohmann::json{{"error", reply.error}};
    if (reply.value.is_string()) {
        auto doc = nlohmann::json::parse(reply.value.get<std::string>(), nullptr, false);
        return doc.is_discarded() ? reply.value : doc;
    }
    return reply.value;
}

} // namespace

int main(int argc, char* argv[])
{
    std::map<std::string, std::string> args{{"--remote-module", kNode}, {"--seconds", "30"}};
    for (int i = 1; i + 1 < argc; i += 2) args[argv[i]] = argv[i + 1];
    for (const char* required : {"--runtime", "--modules", "--data", "--tmp"})
        if (args[required].empty()) fail("args", std::string(required) + " is required");
    const std::string runtime = args["--runtime"];

    // liblogos and its hosts find the runtime binaries and the socket dir here.
    setenv("LOGOS_RUNTIME_PATH", (runtime + "/bin/logos_runtime").c_str(), 1);
    setenv("LOGOS_HOST_PLAIN_PATH", (runtime + "/bin/logos_host_plain").c_str(), 1);
    setenv("LOGOS_HOST_REMOTE_PATH", (runtime + "/bin/logos_host_remote").c_str(), 1);
    setenv("TMPDIR", args["--tmp"].c_str(), 1);

    logos::host::LogosCore::Config config;
    config.shellName = kShell;
    config.modulesDirs = {args["--modules"]};
    config.bundledModulesDirs = {runtime + "/modules"};
    config.persistenceBasePath = args["--data"];
    config.peeringConfigJson = nlohmann::json{{"name", "bc-watch"}}.dump();
    logos::host::LogosCore core(argc, argv, config);
    core.start();
    emit("start", kShell);

    auto peering = core.client<PeeringModule>();
    const std::string invite = firstLine(!args["--link-local"].empty() ? args["--link-local"] : args["--invite"]);
    const std::string peer = inviteRuntimeId(invite);
    const LogosMap redeemed = peering.redeemInvite(invite, std::nullopt);
    if (redeemed.contains("error")) fail("pair", redeemed["error"].dump());
    const bool paired = waitFor(std::chrono::seconds(30), [&] {
        for (const auto& p : peering.peers().value("peers", LogosMap::array()))
            if (p.value("runtime_id", "") == peer) return true;
        return false;
    });
    if (!paired) fail("pair", "the pairing did not complete");
    emit("paired", peer);

    const LogosMap rule = {{"from", peer}, {"module", args["--remote-module"]},
                           {"allowed_callers", {kShell}}, {"events", true}};
    if (const LogosMap set = peering.setImport(kNode, rule); set.contains("error"))
        fail("import", set["error"].dump());
    const bool ready = waitFor(std::chrono::seconds(60), [&] {
        return peering.importStates().value(kNode, LogosMap::object()).value("state", "") == "ready";
    });
    if (!ready) fail("import", peering.importStates().dump());
    emit("import_ready", kNode);

    auto node = core.client<BlockchainModule>();
    logos::CallError error;
    const nlohmann::json info = valueOf(node.get_cryptarchia_info(&error));
    if (!error.ok()) fail("node", error.code + ": " + error.message);
    emit("node", info);

    std::atomic<int> blocks{0};
    auto subscription = node.onNewBlock([&](const std::string&) { ++blocks; });
    std::this_thread::sleep_for(std::chrono::seconds(std::stoi(args["--seconds"])));
    emit("blocks", nlohmann::json{{"new_block_events", blocks.load()}});
    return 0;
}
